# Generated by Django 5.2.6 on 2026-04-21 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-K (con guion y sin puntos)', regex='^\\d{7,8}-[0-9kK]$')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-K (con guion y sin puntos)', regex='^\\d{7,8}-[0-9kK]$')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.CharField(max_length=100)),
                ('resultado', models.FileField(upload_to='documentos/')),
                ('informe', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.paciente')),
            ],
        ),
    ]
